[package]
name = "dantalian"
version = "0.1.0"
authors = ["Nanozuki Crows <nanozuki.crows@gmail.com>"]
edition = "2018"
description = "A nfo file generator for your anime. Source from https://bangumi.tv/."
license-file = "LICENSE"
repository = "https://github.com/nanozuki/dantalian/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
